In [ ]:
import numpy as np

                                      Difference between ARRAY & LIST


- ARRAY

In [2]:
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- LIST

In [3]:
y=[1,2,3,4,5]
print(y)
print(type(y))


[1, 2, 3, 4, 5]
<class 'list'>


                       Advantages of using Numpy Arrays Over Python Lists:

- Data type storage-->
- In List--> Store different type of element.(eg- a=[1,9.4,'hey'])
- In Array--> Store similar type of element.(eg- a= numpy.arange([1,2,3]))
- Importing module
- Numerical operation--> List has less numerical operation so List is less efficient and visa-versa.
- Modification Capabilities--> List have more modification capabilities than Array.

- Consumes less memory.
- Fast as compared to the python List.
- Convenient to use


In [ ]:
# importing system module for list
import sys

# declaring a list of 100 elements
S= range(100)
print(S)


# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
# declaring a Numpy array of 100 elements
D= np.arange(100)
print(D)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

                          how array is faster than list?

- %timeit --> It is used for know the execution time of "ONE LINE".
- %%timeit --> It is used for know the execution time of "PROGRAM".

In [11]:

%timeit [j**4 for j in range(1,9)]

2.58 µs ± 72.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
import numpy as np

In [16]:
%timeit np.arange(1,9)**4

3.96 µs ± 86.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array


    Creation of Array

In [26]:
x=[1,2,3]
y=np.array(x) # One method
z=np.array([1,2,3,4]) # Second method
print(y,'\n',z)

# type of array
z # method 1
print(type(y)) # method 2


[1 2 3] 
 [1 2 3 4]
<class 'numpy.ndarray'>


    Taking input in array.

In [24]:
l=[]

for i in range(1,5):
    #a=input("Enter Number: ") #takes input in string data types by default.
    a=int(input("Enter Number: "))
    l.append(a)
print(np.array(l)) # creating array and copying the list element into array.

[8 6 9 0]


    Dimenstion of array using .ndim

In [27]:
print(z.ndim)

1


    Creation of n-dimension Array

In [33]:
# creating 2,3-dimension array

ar2=np.array([[8,9,0],[4,5,6]])
#ar2=np.array([[8,9,0],[4,5,6,7]]) #TypeError: Field elements must be 2- or 3-tuples, got '4'
print(ar2)
print(ar2.ndim)

# creating n- dimension array

arn=np.array([1,2,3,4],ndmin=10)
print(arn,'\n',arn.ndim)

[[8 9 0]
 [4 5 6]]
2
[[[[[[[[[[1 2 3 4]]]]]]]]]] 
 10


# Special numpy Array

    Array filled with 0's

In [36]:
ar_zero=np.zeros(4) # 4 element of zeros.
print(ar_zero,'\n')

ar_zero1=np.zeros((3,4)) # zero with dimension.((Row,Col))
print(ar_zero1)

[0. 0. 0. 0.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


    Array filled with 1's

In [37]:
ar_ones=np.ones(4) # 4 element of zeros.
print(ar_ones,'\n')

[1. 1. 1. 1.] 



    Create empty array

In [39]:
ar_emp=np.empty(4) #size=4
print(ar_emp,'\n')
# data of previous memory will came into empty

[1. 1. 1. 1.] 



    An array with range of element.

In [40]:
ar_rn=np.arange(4) 
print(ar_rn,'\n')
# used for creating an array in continous order from zero to n.

[0 1 2 3] 



    Array diagonal element filled with 1's

In [43]:
ar_dia=np.eye(3)
print(ar_dia,'\n')
#n-dim
ar_dia1=np.eye(3,5) #(Row,Col)
print(ar_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


    Create an array with values that are spaced linearly in a specified interval

* Linspace--> know number of element but don't know gap/difference b/w them.

In [47]:
ar_lin=np.linspace(0,20,num=6) #(start,end,number of element in array)
print(ar_lin)

[ 0.  4.  8. 12. 16. 20.]


# Random Number Functions

➤ rand(): the function is used to generate a random value between 0 to 1.

➤ randn(): the function is used to generate a random value close to zero. This may return positive or negative numbers as well.

➤ ranf(): the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half en interval [0.0, 1.0).

➤randint(): the fuction is used to generate a random number given range.

    rand() --> 0 to 1

In [48]:
var=np.random.rand(4)
print(var)

[0.06642785 0.3641681  0.65720714 0.38544465]


In [49]:
var1=np.random.rand(2,5) # (row,col)
print(var1)

[[0.55583788 0.48056381 0.76355185 0.18985    0.92110842]
 [0.49080442 0.76508282 0.66927049 0.00721817 0.34826636]]


    randn() --> negative as well as positive numbers close to zero.

In [50]:
var2=np.random.randn(5) # random --> it will mandatory because it will work through random module.
print(var2)

[-0.2843469   0.45102163 -0.86826597  1.21597874  0.17239412]


    ranf() --> range includes zero but not one.

In [52]:
var3=np.random.ranf(5) #(dataset/element=4)
print(var3)

[0.38580684 0.78304209 0.30612363 0.0669106  0.950673  ]


    randint() --> generate number in range(start_range, end_range)
    

In [57]:
var4=np.random.randint(5,20,9) # randint(min_value, max_value, total_values). not include range between numbers
print(var4)

[14  6 12  6 18  6  9  6  6]
