# Airthmetic Operation on Array

    1-D Array

In [ ]:
import numpy as np

In [ ]:
var1=np.array([1,2,3])
var2=np.array([8,9,0])


In [ ]:
# using functions

var_add=np.add(var1,var2)
print(var_add)

In [ ]:
# using functions

var_add=np.add(var1,3)
print(var_add)

In [ ]:
var_add=var1+3
print(var_add)

In [ ]:
var_add=var1+var2
print(var_add)


In [ ]:
var_sub=var1-3
print(var_sub)

In [ ]:
var_sub=var1-var2
print(var_sub)

In [ ]:
var_mul=var1*3
print(var_mul)

In [ ]:
var_mul=var1*var2
print(var_mul)

In [ ]:
var_div=var1/3
print(var_div)

In [ ]:
var_div=var1/var2
print(var_div)

In [ ]:
var_mod=var1%3
print(var_mod)

In [ ]:
var_mod=var1%var2
print(var_mod)

In [ ]:
var_add=np.reciprocal(var1)
print(var_add)

    2-D Array

In [ ]:
var2d=np.array([[1,2,3],[8,9,0]])
var2d_1=np.array([[1,6,3],[4,6,0]])

var_add=var2d+2

print(var_add)

In [ ]:
var_pow=var2d**2
print(var_pow)

In [ ]:
var_add=var2d+var2d_1
print(var_add)

--------------------------------------------------------------------------------------------------------------------------------

# Shape

    Input= .shape
    Output= (row,col)

In [ ]:
var= np.array([[4,5,6],[7,8,9]])

print(var)
print(var.shape)

In [ ]:
var_n=np.array([8,6,3],ndmin=6)  #! ndmin (=number of dimension)
print(var_n)
print(var_n.ndim)                #!  ndim
print(var_n.shape)

# Reshape

    .reshape(Row=n,Col=n)

In [ ]:
var1=np.array([1,2,3,9,4,2,1,3,2])
print(var1)
print()

x=var1.reshape(9,1) #* (row=9,col=1)
print(x) #& 2-D 
print()
y=var1.reshape(1,9) #* (row=1,col=9)
print(y) #! 2-D 
print()
z=var1.reshape(3,3) #* (row=3,col=3)
print(z) #^ 2-D 
print()




In [ ]:
var1=np.array([1,2,3,9,4,2,2,2,3,5,6,8])  #! (row= 1, col= 12) -> 1-D
     #*    (R= - ,C= | )
u=var1.reshape(1,12)    #% -> 1-D
print(u)
print()
v=var1.reshape(12,1)    #^ -> 2-D
print(v)
print(v.ndim)
print()
w=var1.reshape(4,3)    #^ -> 2-D  How?
print(w)
print(w.ndim)
print()
x=var1.reshape(2,6)    #^ -> 2-D
print(x)
print(x.ndim)
print()
y=var1.reshape(6,2)    #^ -> 2-D
print(y)
print(y.ndim)
print()
z=var1.reshape(3,4)    #^ -> 2-D
print(z)
print(z.ndim)
print()



In [ ]:
var1=np.array([1,2,3,9,4,2,2,2,3,5,6,8])  #! (row= 1, col= 12) -> 1-D

u=var1.reshape(1,12)    #& -> 1-D
print(u)
print()
v=var1.reshape(12,1)    #^ -> 2-D
print(v)
print(v.ndim)
print()

one=v.reshape(-1)
print(one,one.ndim)

# Broadcasting


         1.) Same Dimension
         2.) (a)- : both of the array have 1.
             (b)- : Row/Col same in both.

In [64]:
var1=np.array([1,2,3])
print(var1.shape) #* (row=1,col=3)
var2=np.array([8,9,0,7])
print(var2.shape) #* (row=1,col=4)
print()
#print(var1+var2) #! ValueError: operands could not be broadcast together with shapes (3,) (4,)
print('-'*20)
var1=np.array([1,2,3]) #* (row=1,col=3) {max=3 which is present in both}
print(var1.shape)
var2=np.array([[1],[2],[3]]) #* (row=3,col=1)
print(var2.shape)
print()
print(var1+var2) #! No Error : both of the array have 1.
print('-'*20)

(3,)
(4,)

--------------------
(3,)
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
--------------------


In [65]:
var1=np.array([1,2])
print(var1.shape) #* (row=1,col=2)
var2=np.array([[2],[3],[4]])
print(var2.shape) #* (row=3,col=1)
print()
print(var1+var2)     #! No Error : both of the array have 1.

(2,)
(3, 1)

[[3 4]
 [4 5]
 [5 6]]


In [71]:
var1=np.array([[1],[2]])
print(var1.shape)    #* (row=2,col=1)
var2=np.array([[1,2,3],[2,3,4]])
print(var2.shape)    #* (row=2,col=3)
print('-'*20)
print(var1+var2)     #! No Error : Row same

(2, 1)
(2, 3)
--------------------
[[2 3 4]
 [4 5 6]]


In [ ]:
var1=np.array([1,2])
print(var1.shape)    #* (row=1,col=2)
var2=np.array([[1,2,3],[2,3,4]])
print(var2.shape)    #* (row=2,col=3)
print('-'*20)
print(var1+var2)   #! ValueError: operands could not be broadcast together with shapes (2,) (2,3)

In [70]:
var1=np.array([1,2])
print(var1.shape)    #* (row=1,col=2)
var2=np.array([[1,2],[2,3],[5,6]])
print(var2.shape)    #* (row=3,col=2)
print('-'*20)
print(var1+var2)    #! No Error : Column same

(2,)
(3, 2)
--------------------
[[2 4]
 [3 5]
 [6 8]]
