# Airthmetic Operation on Array

    1-D Array

In [2]:
import numpy as np

In [3]:
var1=np.array([1,2,3])
var2=np.array([8,9,0])


In [12]:
# using functions

var_add=np.add(var1,var2)
print(var_add)

[ 9 11  3]


In [13]:
# using functions

var_add=np.add(var1,3)
print(var_add)

[4 5 6]


In [3]:
var_add=var1+3
print(var_add)

[4 5 6]


In [4]:
var_add=var1+var2
print(var_add)


[ 9 11  3]


In [4]:
var_sub=var1-3
print(var_sub)

[-2 -1  0]


In [6]:
var_sub=var1-var2
print(var_sub)

[-7 -7  3]


In [11]:
var_mul=var1*3
print(var_mul)

[3 6 9]


In [10]:
var_mul=var1*var2
print(var_mul)

[ 8 18  0]


In [9]:
var_div=var1/3
print(var_div)

[0.33333333 0.66666667 1.        ]


In [ ]:
var_div=var1/var2
print(var_div)

In [7]:
var_mod=var1%3
print(var_mod)

[1 2 0]


In [8]:
var_mod=var1%var2
print(var_mod)

[1 2 0]


C:\Users\hp\AppData\Local\Temp\ipykernel_3408\1237251510.py:1: RuntimeWarning: divide by zero encountered in remainder
  var_mod=var1%var2


In [23]:
var_add=np.reciprocal(var1)
print(var_add)

[1 0 0]


    2-D Array

In [21]:
var2d=np.array([[1,2,3],[8,9,0]])
var2d_1=np.array([[1,6,3],[4,6,0]])

var_add=var2d+2

print(var_add)

[[ 3  4  5]
 [10 11  2]]


In [19]:
var_pow=var2d**2
print(var_pow)

[[ 1  4  9]
 [64 81  0]]


In [22]:
var_add=var2d+var2d_1
print(var_add)

[[ 2  8  6]
 [12 15  0]]


--------------------------------------------------------------------------------------------------------------------------------

# Shape