# Indexing

In [25]:
import numpy as np

In [ ]:
#! 2-D Array
var1=np.array([[3,7],[8,5]])
print(var1.ndim)
print(var1[0,1])

In [ ]:
#! 3-D Array
var2=np.array([[[1,2],[5,6]]])

print(var2)
print(var2.ndim)
print(var2[0,1,0])

# Slicing

    [Start:Stop:Step]

In [15]:
var=np.array([2,3,4,5,6,7])
print(var)
print("2 to 5 : ",var[0:4])
print("3 to end : ",var[1:])
print("start to end : ",var[:5])
print("stop : ",var[::])
print("stop : ",var[:])
print("stop : ",var[::2])
print("stop : ",var[1:4:2])

[2 3 4 5 6 7]
2 to 5 :  [2 3 4 5]
3 to end :  [3 4 5 6 7]
start to end :  [2 3 4 5 6]
stop :  [2 3 4 5 6 7]
stop :  [2 3 4 5 6 7]
stop :  [2 4 6]
stop :  [3 5]


In [19]:
var1=np.array([[1,2,3,4,5],[0,9,8,7,6],[9,4,2,1,6]])
print("9 to 7",var1[1,1:-1])

9 to 7 [9 8 7]


# Iteration

In [23]:
var1=np.array([[1,2,3,4,5],[0,9,8,7,6]])      #* 2-D

#! for each row in array
for i in var1:
    print(i)

print()
print('-'*20)

#! for each element in row
for j in var1:
    for k in j:
        print(k)

[1 2 3 4 5]
[0 9 8 7 6]

--------------------
1
2
3
4
5
0
9
8
7
6


In [ ]:
var1=np.array([[[1,2,3,4,5],[0,9,8,7,6],[9,4,3]]])  #* 3-D


#! for each element in row
for j in var1:
    for k in j:
        for l in k:
            print(l)

        

In [27]:
var1=np.array([[[1,2,3,4,5],[0,9,8,7,6]]])  #* 3-D


#! for each element in row
for j in np.nditer(var1):
    print(j)

1
2
3
4
5
0
9
8
7
6


In [28]:
var1=np.array([[[1,2,3,4,5],[0,9,8,7,6]]])  #* 3-D


#! for each element in row with index
for i,d in np.ndenumerate(var1):
    print(i,d)  #! (index,data)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 0
(0, 1, 1) 9
(0, 1, 2) 8
(0, 1, 3) 7
(0, 1, 4) 6


# Copy VS View

In [31]:
var=np.array([1,2,3,4])
co=var.copy()
var[1]=40
print("var : ",var)
print("copy : ",co)
print("-"*30)
vi=var.view()
var[2]=7
print("var : ",var)
print("view : ",vi)

var :  [ 1 40  3  4]
copy :  [1 2 3 4]
------------------------------
var :  [ 1 40  7  4]
view :  [ 1 40  7  4]


# Join Function

- concatenate= join
- stack=merge along with axis (horizontally,Vertically)


In [34]:
var1=np.array([1,2,3,4])
var2=np.array([14,62,6,4])
ar=np.concatenate((var1,var2))
print(ar)

[ 1  2  3  4 14 62  6  4]


In [40]:
var1=np.array([[1,2,3,4],[7,4,3,2]])
var2=np.array([[8,6,6,4],[7,3,2,1]])
ar=np.concatenate((var1,var2),axis=1)
ar=np.concatenate((var1,var2),axis=0)
print(ar)


[[1 2 3 4]
 [7 4 3 2]
 [8 6 6 4]
 [7 3 2 1]]


In [43]:
var1=np.array([1,2,3,4])
var2=np.array([14,62,6,4])
ar=np.stack((var1,var2),axis=1)
ar=np.stack((var1,var2),axis=0)  #! merge along with axis
print(ar)

[[ 1 14]
 [ 2 62]
 [ 3  6]
 [ 4  4]]


In [49]:
var1=np.array([1,2,3,4])
var2=np.array([14,62,6,4])
ar=np.hstack((var1,var2))  #! merge along with row
print(ar)
print()
ar=np.vstack((var1,var2))  #! merge along with col
print(ar)
print()
ar=np.dstack((var1,var2))  #! merge along with height
print(ar)

[ 1  2  3  4 14 62  6  4]

[[ 1  2  3  4]
 [14 62  6  4]]

[[[ 1 14]
  [ 2 62]
  [ 3  6]
  [ 4  4]]]


# Split function

In [52]:
var1=np.array([1,2,3,4])
ar=np.array_split(var1,3)
print(ar)
print(type(ar))
print(ar[0])

[array([1, 2]), array([3]), array([4])]
<class 'list'>
[1 2]


In [54]:
var1=np.array([[1,2],[3,4],[5,7]])
ar=np.array_split(var1,3)
print(ar)
print(type(ar))
print(ar[0])
print()
ar=np.array_split(var1,3,axis=1)
print(ar)

[array([[1, 2]]), array([[3, 4]]), array([[5, 7]])]
<class 'list'>
[[1 2]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [7]]), array([], shape=(3, 0), dtype=int32)]


# Numpy Array Functions

- Search Function

     ➤ Search Array : Search an array for a certain value, and return the indexes that get a match.

In [64]:
var1=np.array([1,2,3,4,2,2])
x=np.where(var1==2)
print(x)

(array([1, 4, 5], dtype=int64),)


In [65]:
var1=np.array([1,2,3,4])
x=np.where((var1%2)==0)
print(x)

(array([1, 3], dtype=int64),)


     ➤ Search Sorted Array : Array which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [68]:
var1=np.array([1,2,3,4])
x=np.searchsorted(var1,5)
print(x)
x=np.searchsorted(var1,5,side="right")
print(x)
x=np.searchsorted(var1,[5,2,7],side="right")
print(x)

4
4
[4 2 4]


- Sort Function

    ➤ Sort Array: Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [69]:
var1=np.array([7,9,3,4,6])
print(np.sort(var1))

[3 4 6 7 9]


In [70]:
var1=np.array(['n','h','g','a'])
print(np.sort(var1))

['a' 'g' 'h' 'n']


In [71]:
var1=np.array([[7,9,3],[4,6,3]])
print(np.sort(var1))

[[3 7 9]
 [3 4 6]]


- Filter Array

     ➤ Filter Array: Getting some elements out of an existing array and creating a new array out of them.

In [73]:
var1=np.array(['n','h','g','a'])
f=[True,False,True,False,]
ar=var1[f]
print(ar)
print(type(ar))

['n' 'g']
<class 'numpy.ndarray'>


# Insert Function 

In [88]:
var1=np.array([7,9,3,4,6])
v=np.insert(var1,3,8)  #* insert(array,pos,value)
print(v)
v=np.insert(var1,3,8.2)  #! insert --> take only integer value
print(v)
x=np.insert(var1,(3,4),8)   #* multiple position
print(x)

[7 9 3 8 4 6]
[7 9 3 8 4 6]
[7 9 3 8 4 8 6]


In [83]:
var1=np.array([[7,9,3],[4,6,2]])
v=np.insert(var1,2,8,axis=1)  #* insert(array,pos,value,axis=0/1/..)   work acc to col
print(v)
print('-'*20)
w=np.insert(var1,2,8,axis=0) #* work acc to row
print(w)
print('-'*20)
x=np.insert(var1,2,[8,2],axis=1) #* multiple values
print(x)


[[7 9 8 3]
 [4 6 8 2]]
--------------------
[[7 9 3]
 [4 6 2]
 [8 8 8]]
--------------------
[[7 9 8 3]
 [4 6 2 2]]


In [89]:
var1=np.array([7,9,3,4,6])
v=np.append(var1,8)  
v=np.append(var1,8.3)  #! append --> take float and integer value both.
print(v)

[7.  9.  3.  4.  6.  8.3]


In [96]:
var1=np.array([[7,9,3],[4,6,2]])
x=np.append(var1,[[80,20,65]],axis=0)
print(x)


[[ 7  9  3]
 [ 4  6  2]
 [80 20 65]]


In [ ]:
var1=np.array([[7,9,3],[4,6,2]])
y=np.append(var1,[[89,23,5]],axis=1)   #! Error
print(y)

# Delete

In [101]:
var1=np.array([7,9,3,4,6])
v=np.delete(var1,3) 
print(v) 

[7 9 3 6]


# Matrix

    Difference between Array and Matrix

In [102]:
var=np.matrix([[1,2,3],[4,5,5]])
print(var)
print(type(var)) #^ (1.) Class different 

[[1 2 3]
 [4 5 5]]
<class 'numpy.matrix'>


In [111]:
var=np.array([[1,2,3],[4,5,5]])
print(var)
print(type(var)) #^ (1.) Class different
print('-'*40)
print(var*var)

print('-'*40)

[[1 2 3]
 [4 5 5]]
<class 'numpy.ndarray'>
----------------------------------------
[[ 1  4  9]
 [16 25 25]]
----------------------------------------


In [104]:
var1=np.matrix([[1,2,3],[4,5,5]])
var2=np.matrix([[1,6,1],[7,9,5]])
print(var1+var2)

[[ 2  8  4]
 [11 14 10]]


In [ ]:
var1=np.matrix([[1,2,6],[5,5,4]])
var2=np.matrix([[1,6,7],[9,5,4]])

#* Error?

print(var1*var2)   #!  ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)
print(var1.dot(var2))     #!  ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
var1=np.matrix([[1,2],[5,5]])
var2=np.matrix([[1,6],[9,5]])
print(var1*var2)   #!  ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

print('-'*40)



print(var1.dot(var2)) #^ Multiplication of matrix done when broadcast condition meet.


    Matrix Functions

- Transpose - Change axis of matrix.

- Swapaxes

- Inverse

- Power

- Determinant

In [119]:
var1=np.matrix([[1,2],[5,5]])
print(np.transpose(var1)) #^ transpose Matrix
print(var.T) #& Alternate of transpose matrix

[[1 5]
 [2 5]]
[[1 4]
 [2 5]
 [3 5]]


In [120]:
var1=np.matrix([[1,2],[5,5]])
print(var1)
print(np.swapaxes(var1,0,1)) #^ Swapaxes Matrix

[[1 5]
 [2 5]]


In [121]:
var1=np.matrix([[1,2],[5,5]])
print(var1)

print(np.linalg.inv(var1)) #^ Inverse Matrix


[[1 2]
 [5 5]]
[[-1.   0.4]
 [ 1.  -0.2]]


In [123]:
var1=np.matrix([[1,2],[5,5]])
print(var1)
print('-'*40)

print(np.linalg.matrix_power(var1,2)) #^ Power Matrix
print('-'*40)

print(np.linalg.matrix_power(var1,0))
print('-'*40)

print(np.linalg.matrix_power(var1,-2))

[[1 2]
 [5 5]]
----------------------------------------
[[11 12]
 [30 35]]
----------------------------------------
[[1 0]
 [0 1]]
----------------------------------------
[[ 1.4  -0.48]
 [-1.2   0.44]]


In [124]:
var1=np.matrix([[1,2],[5,5]])
print(var1)
print('-'*40)
print(np.linalg.det(var1)) #^ Determinant Matrix

[[1 2]
 [5 5]]
----------------------------------------
-4.999999999999999
